import React from "react";
import styles from "./styles.module.css";
import { useResize } from "../Hooks/use-resize";

import {
  aboutMobile,
  aboutTablet,
  aboutDesktop,
} from "../../image/about/index";
import Ticker from "../Ticker/Ticker";
import IconSharp from "../IconSharp/IconSharp";

const About = () => {
  const { isMobile, isDesktop } = useResize();

  return (
    <>
      <section id='about' className={styles.container}>
        {isMobile ? (
          <>
            <div className={styles.title}>
              a Story that started with
              <span className={styles.titleSpan}>
                one simple <p>ape</p>
              </span>
            </div>

            <div className={styles.infoFirst}>
              <p>WHO GOT</p> <p>FED UP WITH BORING</p> <p>AND HYPOCRITIC</p>
              <p>COMMONPLACE THIS IS</p> <p>HOW THE IDEA OF</p>
              <p>ESCAPING AND DYNAMIC</p>
              <p>JOURNEY ON THE YACHT</p>
            </div>
          </>
        ) : (
          <>
            <div className={styles.title}>
              a Story that started with
              <span className={styles.titleSpan}>one simple ape</span>
            </div>
            <div className={styles.infoFirst}>
              WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
              THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE <p>YACHT</p>
            </div>
          </>
        )}
        <div className={styles.iconWrapper}>
          <IconSharp />
        </div>
        <div className={styles.infoTwo}>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </div>

        <img
          src={isDesktop ? aboutDesktop : isMobile ? aboutMobile : aboutTablet}
          alt='aboutImage'
          className={styles.imageAbout}
        />
      </section>
      <Ticker />
    </>
  );
};

export default About;
